### ISSUE TITLE
adding custom action

### ISSUE THREAD

**Issue by everythinginjs** [johnyvelho/admin-bro-users-permissions#3]
hello @johnyvelho is it possible to add custom Action like new, edit I added one but I get the following from your package

`TypeError: Cannot read property 'role' of undefined
    at Object.isAccessible (/Users/amirmahmoodi/Desktop/honaramoozanPanel/node_modules/admin-bro-users-permissions/src/policies/isAccessGranted.js:5:70)
    at ActionDecorator.is (/Users/amirmahmoodi/Desktop/honaramoozanPanel/node_modules/admin-bro/lib/backend/decorators/action/action-decorator.js:191:35)
    at ActionDecorator.isAccessible (/Users/amirmahmoodi/Desktop/honaramoozanPanel/node_modules/admin-bro/lib/backend/decorators/action/action-decorator.js:229:17)
    at /Users/amirmahmoodi/Desktop/honaramoozanPanel/node_modules/admin-bro/lib/backend/decorators/resource/resource-decorator.js:225:131
    at Array.filter (<anonymous>)
    at ResourceDecorator.recordActions (/Users/amirmahmoodi/Desktop/honaramoozanPanel/node_modules/admin-bro/lib/backend/decorators/resource/resource-decorator.js:225:40)
    at BaseRecord.toJSON (/Users/amirmahmoodi/Desktop/honaramoozanPanel/node_modules/admin-bro/lib/backend/adapters/record/base-record.js:293:47)
    at /Users/amirmahmoodi/Desktop/honaramoozanPanel/node_modules/admin-bro/lib/backend/adapters/record/base-record.js:280:38
    at Array.reduce (<anonymous>)
    at BaseRecord.toJSON (/Users/amirmahmoodi/Desktop/honaramoozanPanel/node_modules/admin-bro/lib/backend/adapters/record/base-record.js:276:51)
    at handler (/Users/amirmahmoodi/Desktop/honaramoozanPanel/admin/honramoozanpanel/honaramoozanpanel.installment.js:28:29)
    at /Users/amirmahmoodi/Desktop/honaramoozanPanel/node_modules/admin-bro/lib/backend/decorators/action/action-decorator.js:121:90
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`

**Comment by everythinginjs** [comment]
fixed ✅
